import { cookies } from 'next/headers'
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../app/globals.css";
import RootProvider from "./RootProvider";
import Header from './_common/Header';
import Footer from './_common/Footer';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps) {

  const cookieTheme = (await cookies()).get('theme')?.value;

  return (
      <html lang="ko">

        <head>
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
          <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100..900&display=swap" rel="stylesheet" />
        </head>

        <body 
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
            {/* <ToastContainer/> */}
            <RootProvider>
            <header>
                <Header />
            </header>

            <main>
                {children}
            </main>

            <footer>
                <Footer />
            </footer>
            </RootProvider>
        </body>
    </html>    

  );
}
